### ISSUE TITLE
registration/editing/logining users

### ISSUE THREAD

**Issue by chindruby** [chindruby/ScreenCode#2]
Всі три пункти - це поля, виходить їх потрібно красиво і в одному стилі оформити. 
Сюди не включаємо реєстрацію і вхід на гостьовій сторінці, йде мова про окремі сторінки. 
Плюс, потрібно подумати куди прикрутити лінк на перехід до editing, читай налаштування профілю, це обговорювати тут - моя пропозиція наступна, зробити як на гітхабі, тільки у нас  в хедері буде аватар + нік, а коли нажимаєш на нього має вилітати менюшка, що включає ( перегляд профілю, перегляд усіх своїх скрінкодів, налаштування профілю, вихід ).

**Comment by entersendman** [comment]
Done.
